# site settings
title: Sport Faces
subtitle:
email: info@robbertenfrank.com
description: Een project in het kader van Kortrijk Europese Sportstad 2018 <br/>Frank&Robbert Robbert&Frank i.s.m. Buda VZW, Bubox en Stad Kortrijk.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address:
city:
state:
zip_code:
country:
phone:

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url: https://instagram.com/R_en_F
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
